project:
  type: website
  output-dir: docs

website:
  title: "Jeremy Provance"
  navbar:
    background: dark
    search: true
    left:
      - cv.qmd
      - blog.qmd
    right:
      - icon: twitter
        href: https://twitter.com/jeremyprovance
        aria-label: Twitter
      - icon: mastodon
        href: https://mastodon.world/web/@jeremyprovance
        aria-label: Mastodon
      - icon: linkedin
        href: www.linkedin.com/in/jeremyprovance
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/jeremyprovance
        aria-label: GitHub
    page-footer:
      center:
        - text: "Copyright © `r format(Sys.time(), '%Y')` Jeremy B Provance"
        - href: index.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual


