---
title: "Jeremy Provance"
output: 
  html_document:
    css: css/main.css
---
<nav>
  <ul>
	  <li><a href="/">About</a></li>
    <li><a href="/cv">CV</a></li>
		<li><a href="/running">Running</a></li>
    <li><a href="/blog">Blog</a></li>
	</ul>
</nav>

***

I'm a PhD student at the University of Missouri-Kansas City School of Medicine studying health informatics. My interests are in the intersection of clinical science and technology, specifically how we can leverage data to understand and improve health and health systems. 

My research at the Saint Luke's Mid American Heart Institute is under the mentorship of [Kim Smolderen](http://med.umkc.edu/dir/Smolderen-Kim/). My long term goals are to use health data to better understand chronic disease, disease outcomes, and to empower patients to take an active role in creating better health.

I completed my undergraduate studies in biology at William Jewell College and completed a senior research project studying fermentation. I spent time in industrial beer production, first producing beer at Tallgrass Brewing and then analyzing it at Boulevard Brewing, before attending graduate school. I completed my master's degree in health informatics in 2017.

[Follow me on Twitter!](https://twitter.com/jeremyprovance)

***

<center> Copyright © 2019 Jeremy B Provance </center>

