---
title: "Jeremy B **Provance**, PhD, MS *Curriculum Vitae*"
output:
  pdf_document: default
  html_document:
    css: main.css
---

***

**CONTACT INFORMATION**

Email: [jeremy.provance\@yale.edu](mailto:jeremy.provance@yale.edu)\
Personal Website: [jeremyprovance.github.io](https://jeremyprovance.github.io)\
Institutional Profile: [medicine.yale.edu/profile/jeremy_provance](https://medicine.yale.edu/profile/jeremy_provance/)  
Twitter: [\@jeremyprovance](https://twitter.com/jeremyprovance)

[Vascular Medicine Outcomes Research Group](https://medicine.yale.edu/lab/vamos/)\
[Department of Internal Medicine](https://medicine.yale.edu/intmed/), [Section of Cardiovascular Medicine](https://medicine.yale.edu/intmed/cardio/centers/)\
[Yale University School of Medicine](https://medicine.yale.edu)\
789 Howard Avenue\
New Haven, Connecticut 06519

***

**EDUCATION**

PhD Bioinformatics (2021), University of Missouri-Kansas City School of Medicine  
Dissertation: [*Emerging Methods for Use of Real-World Clinical Data for Cardiovascular Outcomes Research*](https://mospace.umsystem.edu/xmlui/handle/10355/84383)

MS Bioinformatics (2017), University of Missouri-Kansas City School of Medicine  
Thesis: [*Decisional Conflict in Peripheral Artery Disease: Association with Treatment Choice and Health Status*](https://mospace.umsystem.edu/xmlui/handle/10355/60583)

BA Biology (2014), William Jewell College  
Senior Project: *Fermentation Vessel Geometry Effects on Saccharomyces cerevisiae Metabolites with Gas Chromatograph-Mass Spectroscopy Analysis*

***

**PROFESSIONAL EXPERIENCE**

Postdoctoral Associate (2021-), Yale University School of Medicine (New Haven, Connecticut)

Graduate Research Assistant (2017-2021), Saint Luke's Mid America Heart Institute (Kansas City, Missouri)

Software Support Analyst (2015-2021), UMKC School of Medicine

Graduate Instructor (2020-2021), UMKC School of Medicine

Graduate Teaching Assistant (2019), UMKC School of Medicine

Microbiologist (2015), Boulevard Brewing Company (Kansas City, Missouri)

Production Brewer (2014), Tallgrass Brewing Company (Manhattan, Kansas)

***

**PROGRAMMING**

Expert: R, SAS, SQL, Stata, Markdown\
Intermediate: MongoDB, Python, MySQL, PostgreSQL, SPSS\
Working Knowledge: Tableau, PHP, HTML5, CSS, Oracle, Command Line

***

**PEER-REVIEWED PUBLICATIONS**

1. Smolderen KG, Gosch K, Arham A, **Provance JB**, Spertus JA, Poosala AB, Shishehbor M, Safley D, Scott K, Stone N, Mena-Hurtado CI. Patient Knowledge and Preference for Peripheral Artery Disease Treatment. *Circulation: Cardiovascular Care and Outcomes*. Under Review.

2. Smolderen KG, Romain G, **Provance JB**, Mao J, Goodney PP, Henke PK, Sedrakyan A, Mena-Hurtado CI. Guideline Directed Medical Therapy and Long-Term Mortality and Amputation Outcomes in Patients Undergoing Peripheral Vascular Interventions. *Annals of Internal Medicine*. Under review.

3. Brahmandam A, Lee M, Bellamkonda K, **Provance JB**, Sumpio B, Ochoa Chaar CI, Smolderen KG, Mena-Hurtado CI, Guzman RJ. Variability in Antithrombotic Therapy After Infrainguinal Lower Extremity Bypass. *Journal of Vascular Surgery*. Under review.

4. **Provance JB**, Spertus JA, Jones PG, Hoffman MA, Bunte MC, Vogel TR, Mena-Hurtado CI, Smolderen KG. 2022. [Factors Associated with 30-Day Major Amputation in Patients with Critical Limb Ischemia Undergoing Endovascular Peripheral Vascular Intervention](https://pubmed.ncbi.nlm.nih.gov/35603755/). *Vascular Medicine*.

5. Scierka L, Mena-Hurtado CI, Shishehbor M, Spertus JA, Nagpal S, Babrowski T, Bunte MC, Politano A, Humphries M, Kirksey L, Chung J, Alabi O, Soukas P, Parikh S, Faizer R, **Provance JB**, Stone N, Scott K, Fuss C, Pacheco C, Gosch K, Harper-Brooks A, Smolderen KG. 2022. [The Shifting Care and Outcomes for Patients with Endangered Limbs - Critical Limb Ischemia (SCOPE-CLI) Registry: Overview of Study Design and Rationale](https://www.sciencedirect.com/science/article/pii/S2352906722000203). *IJC Heart & Vascularture*.

6. Jelani QUA, Llanos-Chea F, Bogra P, Trejo-Paredes C, **Provance JB**, Huang J, Turner J, Anantha-Narayanan M, Sheikh AB, Smolderen KG, Mena-Hurtado CI. 2021. [Guideline-Directed Medical Therapy in Patients with Chronic Kidney Disease Undergoing Endovascular Procedures for Complex Critical Limb Ischemia](https://pubmed.ncbi.nlm.nih.gov/34706363/). *American Journal of Nephrology*.

7. Pichert MD, Smolderen KG, Castro-Dominguez Y, Jelani QA, Nagpal S, **Provance JB**,  Huang J, Malik AO, Secemsky EA, Derbas LA, Mena-Hurtado CI. 2021. [Trends in Drug Coated Device Use for Peripheral Arterial Disease: Insights from Vascular Quality Initiative](https://journals.sagepub.com/doi/abs/10.1177/1358863X211043567?journalCode=vmjc). *Vascular Medicine*.

8. Smolderen KG, Pacheco C, **Provance JB**, Stone N, Fuss C, Decker C, Bunte M, Jelani Q, Safley DM, Secemsky E, Sepucha K, Spatz ES, Mena-Hurtado CI, Spertus JA. 2020. [Treatment Decisions for Patients with Peripheral Artery Disease and Symptoms of Claudication: Development Process and Alpha Testing of the SHOW-ME-PAD Decision-Aid](https://journals.sagepub.com/doi/10.1177/1358863X20988780). *Vascular Medicine*.

9. Malik AO, Peri-Okonny P, Gosch K, Thomas BT, Mena-Hurtado CI, Hiatt W, Aronow HD, Jones PG, **Provance JB**, Labrosciano C, Jelani Q, Spertus JA, Smolderen KG. 2020. [Association of Perceived Stress with Health Status in Patients with Peripheral Artery Disease](https://www.sciencedirect.com/science/article/pii/S0022399920308758?dgcid=coauthor). *Journal of Psychosomatic Research*.

10.  Peri-Okonny P, Spertus JA, Malik AO, Jackson EA, Shishehbor MH, Mena-Hurtado CI, **Provance JB**, Hejjaji V, Patel S, Gosch KL, Smolderen KG. 2020. [Physical Activity after Treatment for Symptomatic Peripheral Artery Disease](https://www.sciencedirect.com/science/article/pii/S0002914920310808?via%3Dihub). *American Journal of Cardiology*.

11.  Peri-Okonny P, Patel S, Heyligers JM, Spertus JA, Jackson EA, Malik AO, **Provance JB**, Mena-Hurtado CI, Shishehbor MH, Hejjaji V, Gosch KL, Smolderen KG. 2020. [Physical Activity in Patients with Symptomatic Peripheral Artery Disease: Insights from the PORTRAIT Registry](https://www.sciencedirect.com/science/article/pii/S1078588420305281?via%3Dihub). *European Journal of Vascular & Endovascular Surgery*.

12.  Malik AO, Peri-Okonny P, Gosch K, Thomas M, Mena-Hurtado CI, Hiatt WR, Jones PG, **Provance JB**, Labrosciano C, Jelani Q, Spertus JA, Smolderen KG. 2020. [Association of Perceived Stress Levels with Long-Term Mortality in Patients with Peripheral Artery Disease](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2767517?guestAccessKey=fdb3baf2-0c3d-4daf-91cf-eb996148b474&utm_source=jps&utm_medium=email&utm_campaign=author_alert-jamanetwork&utm_content=author-author_engagement&utm_term=1m). *Journal of the American Medical Association Network Open*.

13.  **Provance JB**, Spertus JA, Decker C, Jones PG, Smolderen KG. 2019. [Assessing Patient Preferences for Shared Decision-Making in Peripheral Artery Disease: Insights from the PORTRAIT Registry](https://www.ahajournals.org/doi/full/10.1161/CIRCOUTCOMES.119.005730). *Circulation: Cardiovascular Quality and Outcomes*.

14.  Ward-Smith P, Hawks JH, Quallich SA, **Provance JB**. 2018. [Workplace incivility: Perceptions of urology nurses](https://library.suna.org/suna/articles/1215/view). *Urological Nursing*.

15.  Hoffman MA, **Provance JB**. 2017. [Visualization of Molecular Structures Using HoloLens-based Augmented Reality](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5543343/). *American Medical Informatics Association Joint Summits on Translational Science Meeting Proceedings*.

***

**PUBLISHED ABSTRACTS**

1. Hu JR, Smolderen KG, **Provance JB**, Romain G, Baumbach A, Velazquez EJ, Lorusso F, Churchwell K, Schulz WL, Scierka LE, Mena-Hurtado CI. 2022. Guideline Directed Medical Therapy After Peripheral Vascular Intervention and Association with Long-term Outcomes at an Academic Health System. *American Heart Association*. Submitted.

2. SCOPE-CLI Consortium. 2022. Familiarity with Disease Terminology in Patients with a Diagnosis of Critical Limb Ischemia: Insights from the SCOPE-CLI Registry. *American Heart Association*. Submitted.

3. SCOPE-CLI Consortium. 2022. A Call to Action for Mental Health Needs Among Patients Diagnosed with Critical Limb Ischemia: Insights from the SCOPE-CLI Registry. *American Heart Association*. Submitted.

4. Smolderen KG, Scierka LE, Romain G, **Provance JB**, Mena-Hurtado CI. 2022. Health System Integrated Measurement-Based Care Using Patient-Reported Outcomes Assessment in Lower-Extremity Peripheral Artery Disease. *American Heart Association*. Submitted.

5. Scierka LE, Mena-Hurtado CI, **Provance JB**, Smolderen KG. 2022. Integrating Mental Health Screening into a Health System Integrated Measurement-Based Care for Patients with Peripheral Artery Disease. *American Heart Association*. Submitted.

6. **Provance JB**, Spertus JA, Jones PG, Hoffman MA, Bunte MC, Vogel TR, Mena-Hurtado CI, Smolderen KG. 2022. [Rates of Guideline Directed Medical Therapy in Patients with Critical Limb Ischemia Undergoing Major Amputation: Insights from the National Cerner Health Facts Electronic Record Database](https://www.jacc.org/doi/10.1016/S0735-1097%2822%2902762-0). *American College of Cardiology*.

7. Lee M, Smolderen KG, Harris KM, Romain G, Scierka LE, **Provance JB**, Mena-Hurtado CI. 2022. [Lower-Extremity Symptoms an Ankle-Brachial Index Screening as Predictors of Cardiovascular Outcomes in Black Adults: Insights from the Jackson Heart Study](https://www.jacc.org/doi/full/10.1016/S0735-1097%2822%2902736-X). *American College of Cardiology*.

8. **Provance JB**, Smolderen KG, Mao J, Goodney PP, Henke PK, Sedrakyan A, Mena-Hurtado CI. 2021. [Guideline Directed Medical Therapy After Peripheral Vascular Intervention And One-year Mortality In Patients With Peripheral Artery Disease In The Vascular Quality Initiative Medicare Linked Database](https://www.abstractsonline.com/pp8/?_ga=2.194332461.18622517.1628715498-1850237547.1616596165#!/9349/presentation/9377). *American Heart Association*.

9.  Rajagopal G, **Provance JB**, Abu Kishk M, Drees BM. 2021. [Predictors of Non-Traumatic Lower Extremity Amputation in Patients with Diabetes and Peripheral Artery Disease](https://diabetesjournals.org/diabetes/article/70/Supplement_1/1053-P/140338/1053-P-Predictors-of-Nontraumatic-Lower-Extremity). *American Diabetes Association*.

10.  **Provance JB**, Spertus JA, Jones PG, Bunte MC, Vogel TR, Hoffman MA, Mena-Hurtado CI, Anderson BS, Smolderen KG. 2020. [Factors Associated with 30-Day Amputation in Patients with Critical Limb Ischemia Undergoing Endovascular Intervention](https://www.jacc.org/doi/abs/10.1016/S0735-1097%2821%2902586-9). *American College of Cardiology*.

11.  **Provance JB**, Spertus JA, Jones PG, Bunte MC, Vogel TR, Hoffman MA, Mena-Hurtado CI, Smolderen KG. 2020. [Site Variability in 30-Day Amputation Rates Among Patients with Critical Limb Ischemia Undergoing Endovascular Intervention](https://www.jacc.org/doi/abs/10.1016/S0735-1097%2821%2902583-3). *American College of Cardiology*.

12.  **Provance JB**, Spertus JA, Decker C, Buchanan D, Jones P, Smolderen KG. 2019. [Preferences and Patterns of Shared Decision-Making in Patients With Peripheral Artery Disease: Insights From the PORTRAIT Registry](http://www.onlinejacc.org/content/73/9_Supplement_1/3006.abstract). *Journal of the American College of Cardiology*.

13.  Peri-Okonny P, Malik A, **Provance JB**, Hejjaji V, Gosch K, Spertus JA, Smolderen KG. 2019. [Cross Country Comparison of Leisure Time Physical Activity Trajectories in Patients With Symptomatic Peripheral Artery Disease: Insights From the PORTRAIT Registry](http://www.onlinejacc.org/content/73/9_Supplement_1/2100.abstract). *Journal of the American College of Cardiology*.

14.  Peri-Okonny P, Malik A, **Provance JB**, Hejjaji V, Gosch K, Spertus JA, Smolderen KG. 2019. [Leisure Time Physical Activity After Invasive Treatment For Symptomatic Peripheral Artery Disease: Insights From the PORTRAIT Registry](http://www.onlinejacc.org/content/73/9_Supplement_1/2093.abstract). *Journal of the American College of Cardiology*.

15.  Malik AO, Peri-Okonny P, **Provance JB**, Gosch K, Thomas M, Labrosciano C, Spertus JA, Smolderen KG. 2019. [The Association of Perceived Stress With Health Status Outcomes in Patients With Peripheral Artery Disease](http://www.onlinejacc.org/content/73/9_Supplement_1/2081.abstract). *Journal of the American College of Cardiology*.

16.  **Provance JB**, Spertus JA, Decker C, Smolderen KG. 2018. [Examining Patients' Knowledge With Regards to Peripheral Artery Disease Treatments and Outcomes: Insights From the PORTRAIT Registry](https://www.ahajournals.org/doi/abs/10.1161/circ.138.suppl_1.15970). *Circulation*. 138: A15970.

17.  **Provance JB**, Spertus JA, Decker C, Smolderen KG. 2018. [How Patients Value Different Treatment Goals and Outcomes in Peripheral Artery Disease Outcomes: Insights From the PORTRAIT Registry](https://www.ahajournals.org/doi/abs/10.1161/circ.138.suppl_1.16038). *Circulation*. 138: A16038.

18. **Provance JB**, Spertus JA, Safley D, Jones PG, Sepucha K, Spatz E, Decker C, Smolderen KG. 2017. [Decisional Conflict in Peripheral Artery Disease: Association with Treatment Choice and Health Status in the PORTRAIT Registry](https://www.ahajournals.org/doi/abs/10.1161/circ.136.suppl_1.20550). *Circulation*. 136: A20550.

***

**PODIUM PRESENTATIONS**

1.  *Visualization of molecular structures using HoloLens-based augmented reality*, Midwest Bioinformatics Conference, 2017 [[video, start at 28:35](https://vimeo.com/217083333)]

2.  *Visualization of molecular structures using HoloLens-based augmented reality*, American Medical Informatics Association Joint Summits for Translational Science, 2017

***

**MODERATED POSTER PRESENTATIONS**

1.  [*Preferences and Patterns of Shared Decision-Making in Patients with Peripheral Artery Disease: Insights from the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2019-03-16_Poster.pdf), American College of Cardiology Scientific Sessions, 2019

***

**POSTER PRESENTATIONS**

1. Rates of Guideline Directed Medical Therapy in Patients with Critical Limb Ischemia Undergoing Major Amputation: Insights from the Cerner Health Facts Electronic Health Record Database, American College of Cardiology Scientific Sessions, 2022

2. Guideline Directed Medical Therapy After Peripheral Vascular Intervention and One-Year Mortality in Patients with Peripheral Artery Disease in the Vascular Quality Initiative Medicare Linked Database, American Heart Association Scientific Sessions, 2021

3. [Factors Associated with 30-Day Amputation in Patients with Critical Limb Ischemia Undergoing Endovascular Intervention](https://jeremyprovance.github.io/assets/2021-05-15_Poster-1.pdf), American College of Cardiology Scientific Sessions, 2021

4. [Site Variability in 30-Day Amputation Rates Among Patients with Critical Limb Ischemia Undergoing Endovascular Intervention](https://jeremyprovance.github.io/assets/2021-05-15_Poster-2.pdf), American College of Cardiology Scientific Sessions, 2021

5.  [*Relationship between Catatonia Treatment and Diagnosis Code, Gender, and Location*](https://jeremyprovance.github.io/assets/2020-Group-12-Poster.pdf), UMKC Medical Student Research Summit, 2020

6.  [*Comparing Types of Medications Prescribed and Type of Insurance Regarding Catatonia Diagnosis*](https://jeremyprovance.github.io/assets/2020-Group-13-Poster.pdf), UMKC Medical Student Research Summit, 2020

7.  [*Association Between Insurance Provider and Psychoactive Drug Treatment for Catatonic Patients*](https://jeremyprovance.github.io/assets/2020-Group-14-Poster.pdf), UMKC Medical Student Research Summit, 2020

8.  [*Patterns of Provider-type Encounters for Patients with Peripheral Artery Disease, Insights from the Cerner Health Facts Database*](https://jeremyprovance.github.io/assets/2020_HSSRS_poster.pdf), UMKC *Virtual* Health Sciences Student Research Summit, 2020

9.  [*Catatonic patients given atypical antipsychotics have a significantly longer length of stay Catatonic patients treated early with a benzodiazepine have a significantly shorter length*](https://jeremyprovance.github.io/assets/Group_12_Poster.pdf), UMKC Medical Student Research Summit, 2019

10.  [*The Protective Effects of Smoking on Catatonia*](https://jeremyprovance.github.io/assets/Group_13_Poster.pdf), UMKC Medical Student Research Summit, 2019

11.  [*The Effects of Insurance Status on the Route Type of the Catatonia Medication Prescribed*](https://jeremyprovance.github.io/assets/Group_14_Poster.pdf), UMKC Medical Student Research Summit, 2019

12.  [*Preferences and Patterns of Shared Decision-Making in Patients with Peripheral Artery Disease: Insights from the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2019-03-16_Poster.pdf), Saint Luke's Hospital Annual Research Day, 2019

13.  [*Studying Non-Traumatic, Lower-Limb Amputations in the Cerner Health Facts EMR Database*](https://jeremyprovance.github.io/assets/2019-04-17_Poster.pdf), UMKC Health Sciences Student Research Summit, 2019

14. [*Preferences and Patterns of Shared Decision-Making in Patients with Peripheral Artery Disease: Insights from the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2019-03-16_Poster.pdf), UMKC Health Sciences Student Research Summit, 2019

15. [*Preferences and Patterns of Shared Decision-Making in Patients with Peripheral Artery Disease: Insights from the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2019-03-16_Poster.pdf), UMKC Community of Scholars Research Symposium, 2019

16. [*Examining Patients' Knowledge with Regards to Peripheral Artery Disease Treatments and Outcomes: Insights from the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2018-11-10_Poster2.pdf), American Heart Association Scientific Sessions, 2018

17. [*How Patients Value Different Treatment Goals and Outcomes in Peripheral Artery Disease Outcomes: Insights from the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2018-11-10_Poster.pdf), American Heart Association Scientific Sessions, Chicago, 2018

18. [*The Effect of Language Barrier on Prescribing of Pain Medication for Patients Diagnosed in the Emergency Department with Kidney Stones*](https://jeremyprovance.github.io/assets/Ottman_Poster.pdf), Truman Medical Center Emergency Medicine Resident Research Day, 2018

19. [*Decisional Conflict in Peripheral Arterial Disease: Association with Treatment Choice and Health Status in the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2017-11-11_Poster.pdf), Saint Luke's Hospital Annual Research Day, 2018

20. [*Comparison of a National and a Local Electronic Health Data Warehouse for Clinical Laboratory Quality Improvement Research*](https://jeremyprovance.github.io/assets/2018-04-11_Poster.pdf), Midwest Bioinformatics Conference, 2018

21. [*Decisional Conflict in Peripheral Arterial Disease: Association with Treatment Choice and Health Status in the PORTRAIT Registry*](https://jeremyprovance.github.io/assets/2017-11-11_Poster.pdf), American Heart Association Scientific Sessions, 2017

***

**HONORS & AWARDS**

Ida Bamberger Memorial Research Award, 2021, UMKC School of Medicine

Scientific Writing Program Selection, 2020, Genetics Society of America and BioKansas

3rd Place (Poster), 2019, UMKC Community of Scholars Research Symposium

Ida Bamberger Memorial Research Award, 2019, UMKC School of Medicine

Travel Award, 2019, UMKC School of Graduate Studies

[Sarah Morrison Student Research Award](https://med.umkc.edu/tag/sarah-morrison-student-research-award/), 2018, UMKC Office of Research Administration

Travel Award, 2018, UMKC School of Graduate Studies

Travel Award, 2017, UMKC School of Graduate Studies

Omicron Delta Kappa Honor Society, 2016

Golden Key International Honor Society, 2016

***

**GRANT PARTICIPATION**

2016-2018\
Role: *Electronic Data Warehouse Analyst* (0.2 FTE)\
Project: [Practice-Based Evidence Using Local and National Data for Quality Improvement](https://med.umkc.edu/umkc-tmc-and-childrens-mercy-win-930k-grant-from-cdc/)\
Principal Investigators: Mark Hoffman, PhD; Kamani Lankachandra, MD\
Funding Agency: Center for Disease Control (RFA-OE16-1602)\
Grant amount: \$956,553 (3 years)

***

**TEACHING EXPERIENCE**

Graduate Instructor, Department of Biomedical & Health Informatics, UMKC School of Medicine\
*MEDB 5512: Clinical Trials (2020, 2021)*

Teaching Assistant, Department of Biomedical & Health Informatics, UMKC School of Medicine\
*MEDB 5512: Clinical Trials (2019)*

***

**INVITED PRESENTATIONS & GUEST LECTURES**

*Guideline Directed Medical Therapy After Peripheral Vascular Intervention and One-Year Mortality in Patients with Peripheral Artery Disease in the Vascular Quality Initiative Medicare Linked Database*, 2021, 38th Semi-Annual Meeting, Vascular Study Group of New England.

*Guideline Directed Medical Therapy After Peripheral Vascular Intervention and One-Year Mortality in Patients with Peripheral Artery Disease in the Vascular Quality Initiative Medicare Linked Database*, 2021, Yale Cardiology Imaging Conference, Yale School of Medicine.

*Quality of Care and Outcomes in Patients with Critical Limb Ischemia: Derivation of a Nationwide Cerner Health Facts Vascular Datamart*, 2021, Yale Internal Medicine Faculty Research Forum, Yale School of Medicine [[slides](https://jeremyprovance.github.io/assets/2021-04-28-Yale-Presentation.pdf)]

*Clinical Research Informatics: Information Needs and Systems in the Clinical Research Environment*, 2021, Introduction to Medical Informatics course, UMKC School of Medicine [[slides](https://jeremyprovance.github.io/assets/2021-03-17_Medical-Informatics.pdf)]

[*Preparing Next-generation Scientists for Biomedical Big Data: Artificial Intelligence Approaches*](https://www.futuremedicine.com/doi/10.2217/pme-2018-0145), 2019, Multi-disciplinary Seminar, UMKC School of Medicine [[slides](https://jeremyprovance.github.io/assets/2019-09-24_Slides.pdf)]

*Generalized Linear Mixed Models-Logistic Regression*, 2018, Biostatistics III, UMKC School of Medicine

*Introduction to Digital Open Science*, 2018, Multi-disciplinary Seminar, UMKC School of Medicine [[slides](https://jeremyprovance.github.io/assets/2018-10-23_Slides.pdf)]

*Using Cerner i2b2 and Health Facts for Clinical Trials and General Research*, 2018, Clinical Trials, UMKC School of Medicine

*Visualization of molecular structures using HoloLens-based augmented reality*, 2017, Multi-disciplinary Seminar, UMKC School of Medicine

*Using the De-identified Cerner i2b2 Database as a Research Resource*, 2017, Medical Student Neuroscience Course, UMKC School of Medicine

***

**RESEARCH MENTORSHIP**

Sunny Ruggeri, UMKC School of Nursing, *Doctoral Committee Member* (2021-2023)

Geetha Rajagopal, Medical Student, UMKC School of Medicine (2020-2021)

Medical Student Neuroscience Course Statistical Mentorship, UMKC School of Medicine (2019, 2020)

Fahad Qureshi, Medical Student, UMKC School of Medicine (2019-2020)

***

**PROFESSIONAL SERVICE**

American Medical Informatics Association, *Clinical Informatics Conference* (Reviewer, 2021-)

American Medical Association, *Journal of the American Medical Association Network Open* (Reviewer, 2020-)

American Heart Association, *Quality of Care & Outcomes Research Scientific Sessions* (Abstract Reviewer, 2020-)

Saint Luke's Hospital Research Day (Poster Judge, 2019)

American Heart Association, *Circulation: Cardiovascular Quality and Outcomes* (Reviewer, 2017-)

American Medical Informatics Association, *Informatics Summits* (Abstract Reviewer, 2017-)

***

**PROFESSIONAL MEMBERSHIP**

American College of Cardiology (2019-Present)

American Heart Association (2017-Present)

American Medical Informatics Association (2017-Present)

***

**PODCAST APPEARANCES**

*Role in implementing i2b2 software, how i2b2 facilitates research goals, and challenges within clinical trials*, The Research Rundown Podcast Series, Episode 3, Cerner Corporation, 2018

***

**SERVICE LEADERSHIP**

UMKC Graduate Student Council, *President (2019), Vice President (2018), Secretary (2016, 2017)*

William Jewell College Presidential Mentorship Program, *Mentor* (2019-Present)

UMKC School of Graduate Studies Strategic Planning Committee, *Student Member* (2019)

UMKC School of Graduate Studies Assistantship and Tuition Task Force, *Student Member* (2019)

Golden Key International Honor Society, Inducted 2016, *Treasurer (2016)*

Omicron Delta Kappa Honor Society, Inducted 2016

UMKC Biomedical & Health Informatics Chair Search Committee, *Student Member* (2016-2017)

UMKC Biomedical & Health Informatics Curriculum Committee, *Student Member* (2016-2017)

Phi Gamma Delta-Zeta Phi, Board of Graduate Advisers (2014-Present)

William Jewell College Student Senate, *President (2013), Treasurer (2014, 2012)*

Phi Gamma Delta-Zeta Phi, *Treasurer (2013)*

William Jewell College Cardinal Hosts (2011-2014)

Missouri Boys State Staff Counselor (2010)

Missouri Boys State, *Boys Nation Finalist* (2009)

***

**PERSONAL ACHIEVEMENTS**

Litchfield Hills Road Race *2022*

Providence Half Marathon *2022*

Hospital Hill Half Marathon *2017, 2018, 2019, 2021*

Kansas City Marathon *2010, 2011, 2016, 2019*

Kansas City Half Marathon *2012, 2013, 2018*

Kansas Half Marathon *2014*

Des Moines 5150 Triathlon *2012*

***

[Click here to generate a web PDF of this CV](https://jeremyprovance.github.io/cv/index.pdf)

<center>

Copyright © `r format(Sys.time(), '%Y')` Jeremy B Provance

</center>
