---
title: "Boulevard Brewing Company"
output: 
  html_document:
    css: main.css
---
<nav>
  <ul>
	  <li><a href="/">About</a></li>
    <li><a href="/cv">CV</a></li>
		<li><a href="/running">Running</a></li>
    <li><a href="/blog">Blog</a></li>
	</ul>
</nav>

***

In January 2015 I was lucky to land a position running the microbiology lab at Boulevard Brewing Company in Kansas City, Missouri. This was a fun job that required a lot of quick and critical thinking when I had to make the call whether or not a beer was suitable (as far as micro goes) to release to the public. It was a mixture of old-school micro (making media, incubating samples) with new-school techniques like qPCR.  One new test I implemented was a real-time assay to detect and quantify Brettanomyces (a yeast used in Boulevard's Saison Brett, but can also spoil other beers if you aren't careful) in beer as it ages.

Breweries are not always the cleanest places, so it was important to know the path each beer would travel and know when and how often it was important to test it. In addition to testing, I was responsible for storing and propagating all of the breweries proprietary yeast strains. The yeast that went into each beer regularly started with a little 1 mL vial of yeast in the lab.  Boulevard still produces many great beers year-round and I am proud of the time I was able to spend there.