---
title: "Tallgrass Brewing Company"
output: 
  html_document:
    css: main.css
---
<nav>
  <ul>
	  <li><a href="/">About</a></li>
    <li><a href="/cv">CV</a></li>
		<li><a href="/running">Running</a></li>
    <li><a href="/blog">Blog</a></li>
	</ul>
</nav>

***

Right after I graduated from college, my first full-time job was crafting beers at a midwest regional brewery called Tallgrass Brewing in Manhattan, Kansas. The brewing system at that time was 15 BBL and 100% manual, which means it was surely a labor of love.  I knew how to brew when I joined, but what I learned a lot about is how to produce at scale and how industry functions--teamwork really made the dream work. I was able to contribute some of my science knowledge to the process drawing from my studies and previous internships. At that time we made beers like Pub Ale, 8-Bit, Buffalo Sweat, Ethos IPA, Halcyon Wheat, Velvet Rooster, and Zombie Monkie.

Manhattan was also my first time truly living on my own, my first apartment at the Wareham above Harry's (and therefore first real electric bill), and learning how to navigate in a brand new environment. I spent a lot of time outside of work at Radina's coffee/bakehouse, in Aggieville eating grilled cheese mac & cheese from the Varsity Donut Truck, and went on lots of long runs out in the wide open spaces.
