---
title: "Jeremy's Blog"
output: 
  html_document:
    css: main.css
---
<nav>
  <ul>
	  <li><a href="/">About</a></li>
    <li><a href="/cv">CV</a></li>
		<li><a href="/running">Running</a></li>
    <li><a href="/blog">Blog</a></li>
	</ul>
</nav>

### Online Security in an Age of Hacking and Breaches
#### Published 2018-03-26

The internet and big data have fundamentally changed our world. Some companies make all or part their revenue by collecting and selling digital data. I am not an information security expert and won't claim to be. I don't have decades of depth in this field. I am, however, a concerned citizen (who works with data) who does not default to trusting companies that collect, store, use, and sell my data. These are tricks that I've learned and use to reduce my online footprint.
Some ways to protect your information online:

1. Stop giving out your personal information all together. Sometimes you have to, often it's optional. Everyone (even brick and mortar stores) wants your email address, your phone number, or another piece of information that uniquely identifies you. We need to limit the data we share about ourselves. Just because I bought something at your store and you asked me nicely doesn't mean I owe you my email address. It's nothing personal but I respectfully don't care to share it. The best way to not lose our data is to not share it at all. This isn't always a practical path, thus, continue reading...

2. Have a disposable email account for when you have to give out your email or create a user account against your better judgement. Use these while sharing minimal information about yourself. These accounts can be periodically deleted, along with the spam and marketing emails that went along with them. When we hear of the next data breach, your daily driver account won't be caught in the mess.

3. Stop using your central accounts when signing in. Using your Google or Facebook account to sign in to a platform saves you 10 seconds, but you automatically give companies access to vacuum up vast amounts of data about you. This is especially true if you sign in with these accounts all the time. Think about how connected all of your accounts and data would be in that case. Many companies are in the sole business of selling your data, so at least make it harder for them to connect the dots. Take 10 seconds to create a new account with an email address. Maybe use a disposable one?

4. Even in light of 2 and 3, minimize the number of accounts you use online. This helps you keep track of where you are sharing information and encourages you to purge data and delete accounts from platforms or services you no longer use. The goal is not to end up with no accounts, but to only retain accounts that you actually use. Less is more in this case.

5. Use a password manager that will generate and remember strong (read: long, complex, not easy to hack) passwords for you. This is not letting the website or internet browser remember it--don't do that! There are keychain programs that keep your passwords separate and secure but make them readily accessible when needed. This allows you to use a different password for every account without having to remember all of them. Many breaches occur due to one human error. Remove yourself from the equation so you can't easily give your account passwords out.

6. That being said, use passwords on everything and regularly change all your passwords...including the ones to unlock your devices. Those golden days of "Password123" and using one password for everything are over. Use your finger print or facial landscape if you can--this is not easy to guess or fake. Use intentionally misspelld words, number combinations that have no inherent meaning to you, and put symbols in illogic?al locations to make your password a lot more secure. Be creative. That's the point.

7. Use caution when participating in rewards or membership programs. Some programs might offer great benefits that outweigh potential downsides. Great. Other than those exceptions to the rule, joining a rewards program at a grocery store is like saying "please track every purchase I make so that you can target me with ads for the things you know I will buy." Not worth it in my eyes.

8. STOP SHARING YOUR CONTACT LISTS WITH ONLINE PLATFORMS. When you share your contacts with a platform, you automatically decide it's ok for the platform to have all your contacts' personal information in their database. Did you ask your friend if you could share their phone number, home address, birth date with Facebook? Some people care about that. I care about that. Think about all the people who have your cell phone number. If all of those people shared, complete profiles for you could exist on platforms you've never visited (sometimes called "shadow profiles"). Be a good friend...protect your friends' data.

9. Be careful how you share your location. Check your devices for applications that access your location and know how often they do. If you are using a ride-hailing app, you should probably share your location while you use it. If you are eating dinner somewhere and want to post a pic of that delish shrimp scampi, maybe don't share your GPS coordinates? Where you go, when you were there, how long you were there are all telling of your habits. As a matter of personal safety (stay away, stalkers) and to prevent the entire world knowing where you are, to within 6 feet, it's probably best to leave location out of the equation.

10. Speaking of location, if you wouldn't walk around barefoot in a place...don't join the wifi network. Many public wifi networks are non-secure and prone to being hacked. Never send any sensitive data over unsecured wifi network--always assume someone can see everything you do on a public network. Just because it's available doesn't mean it's safe.

11. This one is big but it's overlooked 99% of the time: pay attention to terms and conditions you agree to. You probably skip over it most of the time (I do it too, sometimes) when you start on a new platform and scan the whole thing for the "I Accept" at the end. When you are receiving a service for free, it's probably because you are agreeing to pay with your data. Does the free cloud storage you are using require you to automatically volunteer all of your photos for use by the company? Do you understand how the social media company you use is going to use your data to advertise? Are you getting premium features for free because your machine's processor is being used to mine cryptocurrency? Companies write these sections in legalese (and actually make it visually unattractive to read) so A) we should encourage companies to lower the reading level of these agreements so that any reader can understand them, and B) until A happens, pay attention if someone raises red flags on a particular company's user agreement.

12. Make companies that are big offenders take notice. If a company is credibly revealed (either on purpose, through leaks, through news reports) to have questionable or egregious data use practices...stop using them. Force them to adapt or die out. I recognize this is the nuclear option. There are some cases where you've got to go-along to get-along. There might be parts of these services that are really important to us and we may have no alternative--I'm there with you. It's completely ok for you and I to disagree on this and for it to be a gray area. We should take a really hard look at the companies who show themselves to be thoughtless about valuing their users' privacy and security. Talk is cheap...meaningful action in this space is really difficult.

Surely there are a lot of other things we can do, but we all have to start somewhere. It's become clear with so many data breaches and controversies that companies often cannot police themselves. Regardless of what you do, make sure you think before sharing data. Let's be more aware about how we share our personal data.

***

<center> Copyright © 2019 Jeremy B Provance </center>
